spring:
  application:
    name: lanayagoBackend

  datasource:
    url: jdbc:mysql://localhost:3306/lanaya_db?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # or create, create-drop, none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # or appropriate dialect for your MySQL version
